language: node_js
node_js:
  - "lts/*"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'  # 设置时区

script:
- npm build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 0cc7f01ed45b1f733775037496f18d6bc67adfd7
  local-dir: ./sources/.vuepress/dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master