language: node_js
node_js:
  - "lts/*"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'  # 设置时区

script:
- npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 48286e3a5cbffe072f57a066ae75738cca177f6b
  local-dir: ./docs/.vuepress/dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master