language: node_js
node_js: 
  - "lts/*"
branches:
  only:
  - master

cache: 
  directories:
  - node_modules
  npm: true

before_install:
  - export TZ='Asis/Shanghai'

install: 
  - npm 

scripts: 
  - npm run build

deploy: 
  provider: pages
  skip-cleanup: true
  github-token: 0cc7f01ed45b1f733775037496f18d6bc67adfd7
  local-dir: .vuepress/dist/
  target-branch: gh-pages
  verbose: true
  on: 
    branch: master
